Desktop + Mobile layout changes
pizza-to-the-polls/power-the-polls pull request #31
Opened 2020-08-24 05:17 UTC by groeneman

Most of Sarah's design changes implemented here. I'm not particularly strong on CSS, so there are a few differences between Sarah's design and what appears here. Most notably, I couldn't figure out how to cleanly shift the "P" logo to the left of the header text without reworking a ton of HTML. If it's very important, perhaps I can look at that as a follow-on PR. I'm sure there are other details I didn't get quite right, happy to give them another look but figured it was better to get the basic changes out without delay.

Dektop (before/after)

<img width="1040" alt="Screen Shot 2020-08-23 at 10 14 08 PM" src="https://user-images.githubusercontent.com/864712/91006433-34ab9c00-e58e-11ea-979d-c84da57da9a2.png">

<img width="970" alt="Screen Shot 2020-08-23 at 10 13 45 PM" src="https://user-images.githubusercontent.com/864712/91006439-383f2300-e58e-11ea-892d-89f206e11184.png">

Mobile (before/after)

![localhost_3333_(iPhone 6_7_8)](https://user-images.githubusercontent.com/864712/91006491-5ad13c00-e58e-11ea-8f7c-14c9bd77136d.png)

![www powerthepolls org_(iPhone 6_7_8)](https://user-images.githubusercontent.com/864712/91006474-52790100-e58e-11ea-8c35-8f6959893a97.png)

2020-08-24 17:53 UTC, mojowen submitted a review, later dismissed

2020-08-24 21:46 UTC, nexussays commented on site/src/components/page-form/page-form.tsx
>        const formCompleted = () => {
My super cool algorithm :'( so sad

2020-08-24 21:50 UTC, nexussays requested changes
Looks good, thanks! Only thing is if you could remove the `on-desktop` mixin so that the default is always consistent and `on-mobile` remains the only modifier.

2020-08-24 21:51 UTC, nexussays commented
Also @groeneman if you don't mind merging in from `master` just to make it a little cleaner since a few branches have since been merged to master.

2020-08-24 23:20 UTC, groeneman commented
> Looks good, thanks! Only thing is if you could remove the `on-desktop` mixin so that the default is always consistent and `on-mobile` remains the only modifier.

@nexussays think I'm confused on this. Our subhead text is totally different on desktop and mobile, and so I think I need both mixins to hide each one on their respective screen sizes. Neither can be shown "by default"

2020-08-25 00:31 UTC, nexussays requested changes
@groeneman any reason the logo image changed? I don't think it should have and the new one is huge (1.5MiB)

2020-08-25 00:36 UTC, nexussays commented
> 
> 
> > Looks good, thanks! Only thing is if you could remove the `on-desktop` mixin so that the default is always consistent and `on-mobile` remains the only modifier.
> 
> @nexussays think I'm confused on this. Our subhead text is totally different on desktop and mobile, and so I think I need both mixins to hide each one on their respective screen sizes. Neither can be shown "by default"

The styles without the mixin are the default. In order to keep that consistent, we treat large screens as the default and make an exception for small screens using `on-mobile`. So if something is hidden on large screens then set `display: none` and `@on-mobile{ display: block; }`, and so forth for padding or whatever else.

2020-08-25 01:19 UTC, groeneman commented
@nexussays re: logo, Sarah specifically requested using a new version of the logo (I think there were some compression effects or a jagged edge in the old one). I did forget to reduce the new file down to an appropriate size, so I just cut a smaller version and committed that along with the source file.

2020-08-25 01:25 UTC, groeneman commented
@nexussays got it, removed `on-desktop`, ready for review again :)

2020-08-25 01:40 UTC, nexussays approved these changes

2020-08-25 02:06 UTC, merged